### ISSUE TITLE
Доказательство теоремы

### ISSUE THREAD

**Issue by mpsnp** [KubSU/Lections#3]
Нужно доказательство этой теоремы:
![image](https://f.cloud.github.com/assets/2770238/1611442/3cab023e-55ac-11e3-9bf6-5c7281e62487.png)

**Comment by vereesa** [comment]
так доказательство сверху ведь, из этих высказываний и вытекает теорема. написано же. это как Теорему Площадей на физике доказали. Сначала рассуждения, потом формулировка. и зачем тебе лекции первого курса?

**Comment by mpsnp** [comment]
Так они же в списке билетов. А то что она уже доказана, не понял. Устал тогда. Спасибо.
