### ISSUE TITLE
Теорема Пикара 

### ISSUE THREAD

**Issue by Mazan19** [KubSU/Lections#7]
![jpg](https://f.cloud.github.com/assets/6389220/1900185/7bfb773c-7c4b-11e3-9b66-c7c956cde63d.jpg)
Как получился переход из предпоследнего неравенства в последнее? Почему K*|y1-y2| < e/2
и может быть там не K, а L ?

**Comment by mpsnp** [comment]
Самого волнует этот вопрос! Но вроде все правильно, в тетради все то же самое...

**Comment by vereesa** [comment]
ему захотелось переименовать константу, разницы же нет,как она называется,главное,что константа.))поэтому К,а не L. а то другое, вроде как по непрерывности по этим аргументам эта фигня меньше e/2.

**Comment by mpsnp** [comment]
Да про первое я уже понял, а почему именно е/2?

**Comment by SoKT** [comment]
я думаю это для простоты доказательства, это не такой уж важный момент что бы доказательство увеличивать в 2 раза вот он его и убрал, е/2 значит e/2, кстати в следующем семестре можно подойти его об этом спросить xD
