### ISSUE TITLE
Линейные однородные системы

### ISSUE THREAD

**Issue by Mazan19** [KubSU/Lections#9]
Что это значит? мб вместо первого знака "= " нужен " - " ?
![jpg](https://f.cloud.github.com/assets/6389220/1920487/92a8568a-7dea-11e3-85a2-352649e50ef6.jpg)

**Comment by mpsnp** [comment]
Нет. Там вроде просто =0 нету. Тогда следующая строка вытекает нормально.

**Comment by mpsnp** [comment]
У меня уже много правок накопилось, сегодня вечером внесу их все.

**Comment by SoKT** [comment]
![3](https://f.cloud.github.com/assets/6029769/1973628/0ccee310-835f-11e3-9610-308caea77e97.png)

**Comment by mpsnp** [comment]
Ну аналогично моему.
